### PR TITLE
Adding username option to Redis connections

### PR DESCRIPTION
**Pull request by craig-rueda**
# Python SDK

## What did you accomplish?

Adds optional `redisUsername` option to client config that allows downstream users to provide a user, along with the existing password which is important in the event that users would like to use a non-default username.

## How do we test the changes introduced in this PR?

Should behave the same as the previous version as the defaults match the current kwarg defaults found in the Redis class (https://github.com/redis/redis-py/blob/master/redis/client.py#L201)

CC - @EmilianoSanchez

### CODE REVIEW

**Comment by craig-rueda** [comment]
Bump - @EmilianoSanchez 😄

**Comment by chillaq** [comment]
Hi Craig, Thanks for the suggestion, I don't see an issue with adding username into redis adapater, we will add next version.

I will let you know once it is released.

Thanks
Bilal

**Comment by craig-rueda** [comment]
Cool! So you're going to make another PR, or would it work to merge this one? :)

Thanks

**Comment by chillaq** [comment]
Hi @craig-rueda , I pushed the fix to development, it will be out with our next release.

Thanks
Bilal

**Pull request closed without merging**
